# .sqa/config.yml - jenkins-pipeline-library configuration file
sqa_criteria:
  qc_style:
    repos:
      thermal-anomaly-segmenter:
        container: testing
        tox:
          tox_file: tox.ini
          testenv:
            - qc.sty
  qc_coverage:
    repos:
      thermal-anomaly-segmenter:
        container: testing
        tox:
          tox_file: tox.ini
          testenv:
            - qc.cov
  qc_security:
    repos:
      thermal-anomaly-segmenter:
        container: testing
        tox:
          tox_file: tox.ini
          testenv:
            - qc.sec

environment:
  GIT_COMMITTER_NAME: "Elena Vollmer"
  GIT_COMMITTER_EMAIL: "elena.vollmer@kit.edu"
  LANG: C.UTF-8

timeout: 600
