version: "3.6"

services:
  testing:
    #container_name: testing
    working_dir: /srv/thermal_anomaly_segmenter
    build:
      context: ./.sqa
    volumes:
      - type: bind
        source: ./
        target: /srv/thermal_anomaly_segmenter
